[package]
name = "bevy_motion_matching"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bvh_anim = "0.4"
bevy_gltf = "0.13"
bevy_third_person_camera = "0.1.10"
bevy_egui = "0.26.0"
